version: "3.3"

services:
  php74:
    container_name: php74
    build: ../php74/
    restart: unless-stopped
    volumes:
      - "${STORAGE_PATH}:/var/project"
      - "../php74/init_base/schedule-cron:/etc/cron.d/schedule-cron"
      - "../php74/php_ini/php.ini:/usr/local/etc/php/php.ini"
      - "../php74/php_ini/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini"
    command: >
      bash -c "chmod 0777 /etc/cron.d/schedule-cron
      && crontab /etc/cron.d/schedule-cron
      && service cron restart
      && php-fpm"
    ports:
      - 3000:3000
      - 3010:3010
    depends_on:
      - mysql57
    networks:
      - dev

  mysql57:
    container_name: mysql57
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - mysql57-data:/var/lib/mysql
    networks:
      - dev

  nginx:
    container_name: nginx
    build: ../nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    depends_on:
      - php74
    volumes:
      - "${STORAGE_PATH}:/var/project"
      - "${LOG_PATH}:/var/log/nginx"
      - ../nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - dev

networks:
  dev:

volumes:
  mysql57-data:
